title: Sbox Docs
description: Sbox Docs
remote_theme: just-the-docs/just-the-docs
nav_enabled: false

url: https://shunianssy.github.io/sbox-docs

aux_links:
  Template Repository: https://github.com/shunianssy/sbox-docs
  